## Introduction to Natural Language Processing

### Install NLTK
```pip install nltk```

In [1]:
import nltk

In [2]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

## In dialog box select all corpus downloads

## 1. Get the Data
- Get the Data from NLTK Corpora
- or Scrape the Data/ Use API

In [28]:
# Corpus - A large collection of text


from nltk.corpus import brown

In [29]:
# Each catagoery corresponds to entire data set
print(brown.categories())
print(len(brown.categories()))

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']
15


In [30]:
data = brown.sents(categories='fiction')#sentences from brown corporus

In [31]:
#1 sentence in fiction category
data[1]


['Scotty', 'did', 'not', 'go', 'back', 'to', 'school', '.']

In [32]:
' '.join(data[1])

'Scotty did not go back to school .'

### Bag of Words Pipeline convert text into numeric data numbers send to classifier and then prediction
- Get the Data/Corpus
- Tokenisationdocument to sentence to word extraction from entire data set
- , Stopward Removal  removing those word which are irrelevant to machine learning algo like is am her i you
- Stemming converting diffrent form of words into base form dog is runing dog run in park it convert both into run 
- Building a Vocab after all the process u are with list of unique words 
- Vectorization 
- Classification

### Tokenisation & Stopword Removal

In [113]:
document = """It was a very pleasant day. The weather was cool and there were light showers. 
I went to the market to buy some fruits."""

sentence = "Send all the 50 documents related to chapters 1,2,3 at apoorv@@"

In [114]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [115]:
sents = sent_tokenize(document)
print(sents)
print(len(sents))

['It was a very pleasant day.', 'The weather was cool and there were light showers.', 'I went to the market to buy some fruits.']
3


In [116]:
sents[0]

'It was a very pleasant day.'

In [117]:
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'apoorv@@']

In [118]:
words = word_tokenize(sentence)

In [119]:
print(words)

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'apoorv', '@', '@']


In [120]:
words


['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'apoorv',
 '@',
 '@']

## Stopwords

In [121]:
from nltk.corpus import stopwords

sw = set(stopwords.words('english'))

In [122]:
print(sw)

{'out', "didn't", 'can', 'my', "you'd", 'until', 'only', 'but', 'won', 'shan', 'what', "wasn't", 'against', "that'll", 'than', 'through', 'been', 'own', "mustn't", 'needn', 't', 'o', 'did', 'your', 'ma', 'in', 'where', 'on', "it's", 'should', 'all', "shouldn't", 'or', 'their', 'so', 'wouldn', 'our', 'and', 'you', 'because', 'weren', 'with', 'just', 'if', 'again', 'didn', 'no', "weren't", 'he', 'such', 'himself', 'does', 'couldn', 'them', 'itself', 'has', "should've", 'hasn', 'mustn', 'aren', 'was', 'by', "you've", 'being', 's', 'here', 'most', "hasn't", 'up', 'yours', 'how', 'theirs', 'there', 'as', "doesn't", 'nor', "shan't", 'me', 'm', "wouldn't", 'shouldn', 'him', 'other', 'herself', 'be', 'd', 'after', 'have', 'yourself', 'down', 'further', "you're", 'before', 're', 'themselves', 'over', 'both', 'same', 'those', "couldn't", 'each', 've', 'at', 'above', 'don', 'while', 'ain', 'y', 'll', 'having', 'doesn', 'the', 'into', "she's", 'its', 'to', 'this', 'these', 'once', 'any', "mightn't

In [123]:
def remove_stopwords(text,stopwords):
    useful_words = [w for w in text if w not in stopwords]
    return useful_words

In [124]:
text = "i am not bothered about her very much"
useful_text = remove_stopwords(text,sw)
print(useful_text)

[' ', ' ', 'n', ' ', 'b', 'h', 'e', 'r', 'e', ' ', 'b', 'u', ' ', 'h', 'e', 'r', ' ', 'v', 'e', 'r', ' ', 'u', 'c', 'h']


In [125]:
text = "i am not bothered about her very much".split()
useful_text = remove_stopwords(text,sw)
print(useful_text)

['bothered', 'much']


In [126]:
'not' in sw

True

### Tokenization using Regular Expression

In [127]:
## for practicing regular expression one can refer to regexpal.com

In [128]:
from nltk.tokenize import RegexpTokenizer

In [129]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]')
useful_text = tokenizer.tokenize(sentence)

In [130]:
useful_text

['S',
 'e',
 'n',
 'd',
 'a',
 'l',
 'l',
 't',
 'h',
 'e',
 'd',
 'o',
 'c',
 'u',
 'm',
 'e',
 'n',
 't',
 's',
 'r',
 'e',
 'l',
 'a',
 't',
 'e',
 'd',
 't',
 'o',
 'c',
 'h',
 'a',
 'p',
 't',
 'e',
 'r',
 's',
 'a',
 't',
 'a',
 'p',
 'o',
 'o',
 'r',
 'v',
 '@',
 '@']

In [131]:
tokenizer = RegexpTokenizer('[a-zA-Z@.]+')
useful_text = tokenizer.tokenize(sentence)

In [132]:
useful_text

['Send',
 'all',
 'the',
 'documents',
 'related',
 'to',
 'chapters',
 'at',
 'apoorv@@']

### Stemming
- Process that transforms particular words(verbs,plurals)into their radical form
- Preserve the semantics of the sentence without increasing the number of unique tokens
- Example - jumps, jumping, jumped, jump ==> jump`

In [133]:
from nltk.stem.snowball import SnowballStemmer, PorterStemmer
from nltk.stem.lancaster import LancasterStemmer
#Snowball Stemmer, Porter, Lancaster Stemmer

In [134]:
ps = PorterStemmer()

In [135]:
ps.stem('jumping')

'jump'

In [136]:
ps.stem('jumps')

'jump'

In [137]:
ps.stem('lovely')

'love'

In [138]:
ps.stem('loving')

'love'

In [139]:
# Snowball Stemmer #It can do for other language also
ss = SnowballStemmer('english')

In [140]:
ss.stem('lovely')

'love'

In [141]:
ss.stem('jumping')

'jump'

In [142]:
## Lemmatization
from nltk.stem import WordNetLemmatizer

wn = WordNetLemmatizer()
wn.lemmatize('jumping')

'jumping'

In [143]:
##Both of them produe the similar effects only one is needeed

### Building a Vocab & Vectorization

In [144]:
# Sample Corpus - Contains 4 Documents, each document can have 1 or more sentences
corpus = [
        'Indian cricket team will wins World Cup, says Capt. Virat Kohli. World cup will be held at Sri Lanka.',
        'We will win next Lok Sabha Elections, says confident Indian PM',
        'The nobel laurate won the hearts of the people.',
        'The movie Raazi is an exciting Indian Spy thriller based upon a real story.'
]

In [145]:
##COnverting each document into feature document
##A dictionary will formed storing all the words and their corresponding indexes 

In [146]:
from sklearn.feature_extraction.text import CountVectorizer

In [147]:
cv = CountVectorizer()##creating an object 

In [148]:
vectorized_corpus = cv.fit_transform(corpus)#fit learn the dictionary transform convert the dictionary

In [149]:
vectorized_corpus

<4x42 sparse matrix of type '<class 'numpy.int64'>'
	with 47 stored elements in Compressed Sparse Row format>

In [150]:
vectorized_corpus = vectorized_corpus.toarray()#to convert matrix into array

In [151]:
len(vectorized_corpus[0])
print(vectorized_corpus[0])

[0 1 0 1 1 0 1 2 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0
 2 0 1 0 2]


In [152]:
#if u want to see the vocuablary

In [153]:
print(cv.vocabulary_)

{'indian': 12, 'cricket': 6, 'team': 31, 'will': 37, 'wins': 39, 'world': 41, 'cup': 7, 'says': 27, 'capt': 4, 'virat': 35, 'kohli': 14, 'be': 3, 'held': 11, 'at': 1, 'sri': 29, 'lanka': 15, 'we': 36, 'win': 38, 'next': 19, 'lok': 17, 'sabha': 26, 'elections': 8, 'confident': 5, 'pm': 23, 'the': 32, 'nobel': 20, 'laurate': 16, 'won': 40, 'hearts': 10, 'of': 21, 'people': 22, 'movie': 18, 'raazi': 24, 'is': 13, 'an': 0, 'exciting': 9, 'spy': 28, 'thriller': 33, 'based': 2, 'upon': 34, 'real': 25, 'story': 30}


In [154]:
len(cv.vocabulary_.keys())

42

In [155]:
# Reverse Mapping!
numbers = vectorized_corpus[2]##second sentence
numbers

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [156]:
##Reverse mapping convert the list of no into sentences

In [157]:
s = cv.inverse_transform(numbers)
print(s)

[array(['hearts', 'laurate', 'nobel', 'of', 'people', 'the', 'won'],
      dtype='<U9')]


#### Vectorization with  Stopword Removal

In [158]:
def myTokenizer(document):
          #from nltk  # convering regural expression 
    words = tokenizer.tokenize(document.lower())#convertig everythong into lower case means Indian and india can be considered as same
    # Remove Stopwords
    words = remove_stopwords(words,sw)
    return words
    

In [159]:
myTokenizer(sentence)


['send', 'documents', 'related', 'chapters', 'apoorv@@']

In [160]:
print(sentence)

Send all the 50 documents related to chapters 1,2,3 at apoorv@@


In [161]:
#we can create our own tokenizer
cv = CountVectorizer(tokenizer=myTokenizer)

In [162]:
vectorized_corpus = cv.fit_transform(corpus).toarray()

In [163]:
print(vectorized_corpus)

[[0 1 0 1 2 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 2]
 [0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 0]]


In [172]:
print(len(vectorized_corpus[0]))

33


In [173]:
cv.inverse_transform(vectorized_corpus)

[array(['capt.', 'cricket', 'cup', 'held', 'indian', 'kohli.', 'lanka.',
        'says', 'sri', 'team', 'virat', 'wins', 'world'], dtype='<U9'),
 array(['confident', 'elections', 'indian', 'lok', 'next', 'pm', 'sabha',
        'says', 'win'], dtype='<U9'),
 array(['hearts', 'laurate', 'nobel', 'people.'], dtype='<U9'),
 array(['based', 'exciting', 'indian', 'movie', 'raazi', 'real', 'spy',
        'story.', 'thriller', 'upon'], dtype='<U9')]

In [174]:
# For Test Data
test_corpus = [
        'Indian cricket rock !',        
]


In [175]:
##DOnt call fit transform here bcoz thsi is test data it will overwite ur own dictionary

In [176]:
cv.transform(test_corpus).toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

### More ways to Create Features
- Unigram - every word as a feature
- Bigrams
- Trigrams
- n-grams 
- TF-IDF Normalisation

In [204]:
sent_1  = ["this is good movie"]
sent_2 = ["this is good movie but actor is not present"]
sent_3 = ["this is not good movie"]


In [197]:
sent_1

'this is good movie'

In [196]:
sent_3

'this is not good movie'

In [198]:
cv = CountVectorizer()

In [200]:
docs = [sent_1,sent_3]
cv.fit_transform(docs).toarray()

array([[1, 1, 1, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

here clasiifier might not distinguish bw sen1 and sent 2 they are alost similar so here it becomes important that negation with 
good is important like not good ok so instead of considering as not a single word we consider not good as a single wore this is
called biagram considering two keywords as a single word where as in unigram every word is a single feature own it own

In [211]:
cv = CountVectorizer(ngram_range=(1,3))#ngram_rang is by default = (1,1) which means unigram feature (2,2) only biagram (1,3)
# all unigram biagram diagram

In [209]:
docs = [sent_1[0],sent_2[0]]
cv.fit_transform(docs).toarray()

array([[0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]], dtype=int64)

In [210]:
cv.vocabulary_

{'this': 20,
 'is': 9,
 'good': 6,
 'movie': 14,
 'this is': 21,
 'is good': 10,
 'good movie': 7,
 'this is good': 22,
 'is good movie': 11,
 'but': 3,
 'actor': 0,
 'not': 17,
 'present': 19,
 'movie but': 15,
 'but actor': 4,
 'actor is': 1,
 'is not': 12,
 'not present': 18,
 'good movie but': 8,
 'movie but actor': 16,
 'but actor is': 5,
 'actor is not': 2,
 'is not present': 13}

## Tf-idf Normalisation

- Avoid features that occur very often, becauase they contain less information
- Information decreases as the number of occurences increases across different type of documents
- So we define another term - term-document-frequency which associates a weight with every term

In [212]:
#like the word also comes in cricket docuent aslso in politics document also in economics document
#TFID product of 2 terms Tf term frequency idf inverse frequency document  
sent_1  = "this is good movie"
sent_2 = "this was good movie"
sent_3 = "this is not good movie"

corpus = [sent_1,sent_2,sent_3]

In [186]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [187]:
tfidf = TfidfVectorizer()


In [188]:
vc = tfidf.fit_transform(corpus).toarray()

In [189]:
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


In [190]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}